lugares = ['campinas', 'peder', 'sertao', 'sousas', 'joaquim']
print(lugares)
print(sorted(lugares))
print(lugares)
print(sorted(lugares, reverse=True))
print(lugares)
lugares.reverse()
print(lugares)
lugares.reverse()
print(lugares)
lugares.sort()
print(lugares)
lugares.sort(reverse=True)
print(lugares)
print(f'Existem {len(lugares)} lugares diferentes')
